// Temas visuales por proyecto: colores (sobrescriben los tokens de src/styles/tokens.css)
// y emojis decorativos. Se guarda el id en page_content.theme. Puro: se usa en SSR y en tests.

export const THEME_IDS = [
  'fiesta',
  'aventura',
  'navidad',
  'fantasia',
  'viaje',
  'tecnologia',
  'princesas',
  'superheroes',
  'deporte',
  'espacio',
  'dinosaurios',
  'mascotas',
  'musica',
  'bebe',
  'boda',
  'verano',
  'halloween',
] as const;
export type ThemeId = (typeof THEME_IDS)[number];
export const DEFAULT_THEME_ID: ThemeId = 'fiesta';

export interface ThemeEmojis {
  /** Título de la sección de niveles ("🏰 Niveles de Contribución"). */
  levels: string;
  /** Título de la sección del mensaje familiar ("💝 Mensaje de Nuestra Familia"). */
  message: string;
  /** Icono grande junto al mensaje familiar. */
  messageIcon: string;
  /** Título del muro de mensajes de apoyo. */
  support: string;
  /** Título de la sección de miembros de la familia. */
  family: string;
  /** Icono del modal de contribución. */
  modal: string;
  /** "Chispas" de los botones de contribuir. */
  spark: string;
  /** Insignia de contribuidor / nivel sin emoji propio. */
  contributor: string;
  /** Muro vacío. */
  empty: string;
  /** Partículas flotantes del hero de cierre (mín. 5). */
  hero: string[];
  /** Confeti de la celebración (mín. 5). */
  confetti: string[];
}

export interface ThemeTexts {
  /** Título de la sección de miembros de la familia ("La Tribu Que Le Da Alas"). */
  familyTitle: string;
  /** Etiqueta del contador de contribuidores ("Héroes"). */
  contributorsStat: string;
  /** Título de la sección de niveles ("Niveles de Contribución"). */
  levelsTitle: string;
  /** Título del mensaje de la familia ("Mensaje de Nuestra Familia"). */
  messageTitle: string;
  /** Título del muro de mensajes de apoyo ("Mensajes de Apoyo"). */
  supportTitle: string;
  /** Texto del muro de apoyo vacío. */
  emptySupport: string;
}

export interface Theme {
  id: ThemeId;
  name: string;
  description: string;
  /** Tres colores para la tarjeta del backoffice y la home: principal, acción, fondo. */
  swatch: [string, string, string];
  colors: Record<string, string>;
  emojis: ThemeEmojis;
  /** Textos fijos de la página que cambian con el tema (los del formulario no). */
  texts: ThemeTexts;
}

const colors = (c: {
  primary: string;
  action: string;
  actionAlt: string;
  yellow: string;
  green: string;
  greenDark: string;
  greenLight: string;
  purple: string;
  purpleDark: string;
  headerBg: string;
  headerText: string;
  headerSubtitle: string;
  bodyFrom: string;
  bodyMid: string;
  bodyTo: string;
  progressFrom: string;
  progressTo: string;
  levelsFrom: string;
  levelsTo: string;
  sectionAccent: string;
  accent: string;
  accentDark: string;
  accentLight: string;
  accentBg: string;
}): Record<string, string> => ({
  '--color-brand-primary': c.primary,
  '--color-brand-orange': c.action,
  '--color-brand-orange-alt': c.actionAlt,
  '--color-brand-yellow': c.yellow,
  '--color-brand-green': c.green,
  '--color-brand-green-dark': c.greenDark,
  '--color-brand-green-light': c.greenLight,
  '--color-brand-purple': c.purple,
  '--color-brand-purple-dark': c.purpleDark,
  '--color-header-bg': c.headerBg,
  '--color-header-text': c.headerText,
  '--color-header-subtitle': c.headerSubtitle,
  '--color-body-bg-from': c.bodyFrom,
  '--color-body-bg-mid': c.bodyMid,
  '--color-body-bg-to': c.bodyTo,
  '--color-section-progress-from': c.progressFrom,
  '--color-section-progress-to': c.progressTo,
  '--color-section-levels-from': c.levelsFrom,
  '--color-section-levels-to': c.levelsTo,
  '--color-section-orange-accent': c.sectionAccent,
  '--color-accent': c.accent,
  '--color-accent-dark': c.accentDark,
  '--color-accent-light': c.accentLight,
  '--color-accent-bg': c.accentBg,
});

export const THEMES: Record<ThemeId, Theme> = {
  fiesta: {
    id: 'fiesta',
    name: '🎉 Fiesta',
    description: 'Naranja, rojo y amarillo. El look de siempre.',
    swatch: ['#d32f2f', '#ff6b35', '#ffcc02'],
    colors: colors({
      primary: '#d32f2f',
      action: '#ff6b35',
      actionAlt: '#f7931e',
      yellow: '#ffcc02',
      green: '#4caf50',
      greenDark: '#2e7d32',
      greenLight: '#8bc34a',
      purple: '#667eea',
      purpleDark: '#764ba2',
      headerBg: '#1f2937',
      headerText: '#f3f4f6',
      headerSubtitle: '#d1d5db',
      bodyFrom: '#bcbec0',
      bodyMid: '#e6e7e8',
      bodyTo: '#a7a8aa',
      progressFrom: '#fff3e0',
      progressTo: '#ffcc02',
      levelsFrom: '#e8f5e8',
      levelsTo: '#c8e6c8',
      sectionAccent: '#e65100',
      accent: '#e91e63',
      accentDark: '#c2185b',
      accentLight: '#f8bbd9',
      accentBg: '#fce4ec',
    }),
    emojis: {
      levels: '🏰',
      message: '💝',
      messageIcon: '🏰',
      support: '💬',
      family: '🌸',
      modal: '🧡',
      spark: '✨',
      contributor: '⭐',
      empty: '👋',
      hero: ['🎉', '✨', '🎊', '💛', '🎁', '⭐', '🎉'],
      confetti: ['🎉', '✨', '🌟', '💫', '🎊', '🎁', '💝', '💛', '⭐'],
    },
    texts: {
      familyTitle: 'La Tribu Que Le Da Alas',
      contributorsStat: 'Héroes',
      levelsTitle: 'Niveles de Contribución',
      messageTitle: 'Mensaje de Nuestra Familia',
      supportTitle: 'Mensajes de Apoyo',
      emptySupport: '¡Sé el primero en dejar un mensaje de apoyo!',
    },
  },
  aventura: {
    id: 'aventura',
    name: '🚴 Aventura',
    description: 'Verde bosque, tierra y cielo. Bicis, montaña y aire libre.',
    swatch: ['#1b5e20', '#388e3c', '#ffd54f'],
    colors: colors({
      primary: '#1b5e20',
      action: '#388e3c',
      actionAlt: '#66bb6a',
      yellow: '#ffd54f',
      green: '#43a047',
      greenDark: '#1b5e20',
      greenLight: '#a5d6a7',
      purple: '#0277bd',
      purpleDark: '#01579b',
      headerBg: '#1b3a2a',
      headerText: '#f1f8e9',
      headerSubtitle: '#c5e1a5',
      bodyFrom: '#dcedc8',
      bodyMid: '#f1f8e9',
      bodyTo: '#c5e1a5',
      progressFrom: '#fff8e1',
      progressTo: '#ffe082',
      levelsFrom: '#e8f5e9',
      levelsTo: '#c8e6c9',
      sectionAccent: '#ef6c00',
      accent: '#2e7d32',
      accentDark: '#1b5e20',
      accentLight: '#a5d6a7',
      accentBg: '#e8f5e9',
    }),
    emojis: {
      levels: '🧭',
      message: '🏕️',
      messageIcon: '🏔️',
      support: '🌲',
      family: '🌞',
      modal: '🚴',
      spark: '🌿',
      contributor: '⛰️',
      empty: '🥾',
      hero: ['🚴', '🏔️', '🌲', '🌞', '🧭', '🌿', '🚵'],
      confetti: ['🚴', '🌲', '🍃', '🌞', '⛰️', '🧭', '💚', '⭐', '🌿'],
    },
    texts: {
      familyTitle: 'El Pelotón Que Empuja',
      contributorsStat: 'Exploradores',
      levelsTitle: 'Etapas de la Ruta',
      messageTitle: 'Mensaje desde el Campamento Base',
      supportTitle: 'Ánimos desde la Cuneta',
      emptySupport: '¡Sé el primero en animar desde la cuneta!',
    },
  },
  navidad: {
    id: 'navidad',
    name: '🎄 Navidad',
    description: 'Rojo, verde y dorado sobre blanco nieve.',
    swatch: ['#b71c1c', '#c62828', '#ffd700'],
    colors: colors({
      primary: '#b71c1c',
      action: '#c62828',
      actionAlt: '#e53935',
      yellow: '#ffd700',
      green: '#2e7d32',
      greenDark: '#1b5e20',
      greenLight: '#81c784',
      purple: '#1565c0',
      purpleDark: '#0d47a1',
      headerBg: '#14532d',
      headerText: '#fff8e1',
      headerSubtitle: '#ffe082',
      bodyFrom: '#dbe9f6',
      bodyMid: '#ffffff',
      bodyTo: '#c9dcec',
      progressFrom: '#fff8e1',
      progressTo: '#ffd700',
      levelsFrom: '#e8f5e9',
      levelsTo: '#c8e6c9',
      sectionAccent: '#b71c1c',
      accent: '#c62828',
      accentDark: '#8e0000',
      accentLight: '#ef9a9a',
      accentBg: '#ffebee',
    }),
    emojis: {
      levels: '🎄',
      message: '🎁',
      messageIcon: '🔔',
      support: '❄️',
      family: '🦌',
      modal: '🎅',
      spark: '⭐',
      contributor: '🎁',
      empty: '🕯️',
      hero: ['🎄', '🎁', '⭐', '❄️', '🔔', '🎉', '✨'],
      confetti: ['❄️', '🎄', '⭐', '🎁', '🔔', '✨', '❤️', '💚', '🌟'],
    },
    texts: {
      familyTitle: 'Los Duendes de Este Regalo',
      contributorsStat: 'Ayudantes',
      levelsTitle: 'Regalos bajo el Árbol',
      messageTitle: 'Carta de Nuestra Familia',
      supportTitle: 'Felicitaciones',
      emptySupport: '¡Sé el primero en dejar una felicitación!',
    },
  },
  fantasia: {
    id: 'fantasia',
    name: '🐉 Fantasía',
    description: 'Morado, oro y azul noche. Dragones y castillos.',
    swatch: ['#4a148c', '#6a1b9a', '#ffca28'],
    colors: colors({
      primary: '#4a148c',
      action: '#6a1b9a',
      actionAlt: '#8e24aa',
      yellow: '#ffca28',
      green: '#00897b',
      greenDark: '#00695c',
      greenLight: '#4db6ac',
      purple: '#5e35b1',
      purpleDark: '#311b92',
      headerBg: '#1a1040',
      headerText: '#ede7f6',
      headerSubtitle: '#b39ddb',
      bodyFrom: '#d1c4e9',
      bodyMid: '#f3e5f5',
      bodyTo: '#b39ddb',
      progressFrom: '#fff8e1',
      progressTo: '#ffd54f',
      levelsFrom: '#ede7f6',
      levelsTo: '#d1c4e9',
      sectionAccent: '#ff8f00',
      accent: '#8e24aa',
      accentDark: '#6a1b9a',
      accentLight: '#ce93d8',
      accentBg: '#f3e5f5',
    }),
    emojis: {
      levels: '🏰',
      message: '📜',
      messageIcon: '🐉',
      support: '🔮',
      family: '🛡️',
      modal: '🐉',
      spark: '✨',
      contributor: '⚔️',
      empty: '🧙',
      hero: ['🐉', '🏰', '⚔️', '✨', '🛡️', '🔥', '🌟'],
      confetti: ['🐉', '✨', '⚔️', '🏰', '🔥', '💜', '⭐', '🌟', '🛡️'],
    },
    texts: {
      familyTitle: 'La Cofradía del Castillo',
      contributorsStat: 'Valientes',
      levelsTitle: 'Tesoros del Reino',
      messageTitle: 'Pergamino de Nuestra Familia',
      supportTitle: 'Mensajes del Reino',
      emptySupport: '¡Sé el primero en escribir en el pergamino!',
    },
  },
  viaje: {
    id: 'viaje',
    name: '✈️ Viaje',
    description: 'Turquesa, arena y coral. Maletas y mapas.',
    swatch: ['#00838f', '#ff7043', '#ffe082'],
    colors: colors({
      primary: '#00838f',
      action: '#ff7043',
      actionAlt: '#ffab91',
      yellow: '#ffe082',
      green: '#26a69a',
      greenDark: '#00695c',
      greenLight: '#80cbc4',
      purple: '#0288d1',
      purpleDark: '#01579b',
      headerBg: '#004d5a',
      headerText: '#e0f7fa',
      headerSubtitle: '#80deea',
      bodyFrom: '#b2ebf2',
      bodyMid: '#fffde7',
      bodyTo: '#80deea',
      progressFrom: '#fff8e1',
      progressTo: '#ffe082',
      levelsFrom: '#e0f2f1',
      levelsTo: '#b2dfdb',
      sectionAccent: '#ff7043',
      accent: '#ff7043',
      accentDark: '#e64a19',
      accentLight: '#ffab91',
      accentBg: '#fbe9e7',
    }),
    emojis: {
      levels: '🧳',
      message: '🗺️',
      messageIcon: '✈️',
      support: '🌍',
      family: '☀️',
      modal: '✈️',
      spark: '🌴',
      contributor: '🌍',
      empty: '📸',
      hero: ['✈️', '🌍', '🧳', '☀️', '🗺️', '🎉', '🌴'],
      confetti: ['✈️', '🌍', '☀️', '🌴', '🧳', '💙', '⭐', '🎉', '🗺️'],
    },
    texts: {
      familyTitle: 'La Tripulación de Este Viaje',
      contributorsStat: 'Viajeros',
      levelsTitle: 'Billetes de Embarque',
      messageTitle: 'Postal de Nuestra Familia',
      supportTitle: 'Postales de Ánimo',
      emptySupport: '¡Sé el primero en enviar una postal!',
    },
  },
  tecnologia: {
    id: 'tecnologia',
    name: '💻 Tecnología',
    description: 'Índigo y cian. Pantallas, cohetes y rayos.',
    swatch: ['#283593', '#3949ab', '#00acc1'],
    colors: colors({
      primary: '#283593',
      action: '#3949ab',
      actionAlt: '#5c6bc0',
      yellow: '#b2ebf2',
      green: '#00acc1',
      greenDark: '#006064',
      greenLight: '#4dd0e1',
      purple: '#3f51b5',
      purpleDark: '#1a237e',
      headerBg: '#0d1b3e',
      headerText: '#e8eaf6',
      headerSubtitle: '#9fa8da',
      bodyFrom: '#c5cae9',
      bodyMid: '#f5f7fb',
      bodyTo: '#9fa8da',
      progressFrom: '#e0f7fa',
      progressTo: '#80deea',
      levelsFrom: '#e8eaf6',
      levelsTo: '#c5cae9',
      sectionAccent: '#00acc1',
      accent: '#3949ab',
      accentDark: '#283593',
      accentLight: '#9fa8da',
      accentBg: '#e8eaf6',
    }),
    emojis: {
      levels: '💻',
      message: '💌',
      messageIcon: '📱',
      support: '💬',
      family: '⚡',
      modal: '🚀',
      spark: '⚡',
      contributor: '🚀',
      empty: '🤖',
      hero: ['🚀', '💻', '📱', '⚡', '✨', '🎉', '🛰️'],
      confetti: ['🚀', '⚡', '💻', '📱', '✨', '💙', '⭐', '🛰️', '🎉'],
    },
    texts: {
      familyTitle: 'El Equipo de Lanzamiento',
      contributorsStat: 'Astronautas',
      levelsTitle: 'Niveles de Energía',
      messageTitle: 'Transmisión de Nuestra Familia',
      supportTitle: 'Mensajes Recibidos',
      emptySupport: '¡Sé el primero en enviar un mensaje a la nave!',
    },
  },
  princesas: {
    id: 'princesas',
    name: '👸 Princesas',
    description: 'Rosa, lila y dorado. Coronas, castillos y unicornios.',
    swatch: ['#ad1457', '#ec407a', '#fce4ec'],
    colors: colors({
      primary: '#ad1457',
      action: '#ec407a',
      actionAlt: '#f06292',
      yellow: '#ffd54f',
      green: '#66bb6a',
      greenDark: '#2e7d32',
      greenLight: '#a5d6a7',
      purple: '#ab47bc',
      purpleDark: '#7b1fa2',
      headerBg: '#4a0d3a',
      headerText: '#fff0f6',
      headerSubtitle: '#f8bbd0',
      bodyFrom: '#fce4ec',
      bodyMid: '#fff5f8',
      bodyTo: '#f3e5f5',
      progressFrom: '#fff8e1',
      progressTo: '#ffe082',
      levelsFrom: '#fce4ec',
      levelsTo: '#f8bbd0',
      sectionAccent: '#ffb300',
      accent: '#ec407a',
      accentDark: '#c2185b',
      accentLight: '#f8bbd0',
      accentBg: '#fce4ec',
    }),
    emojis: {
      levels: '👑',
      message: '💌',
      messageIcon: '👸',
      support: '🪄',
      family: '🏰',
      modal: '👑',
      spark: '✨',
      contributor: '🎀',
      empty: '🦄',
      hero: ['👑', '🦄', '🌸', '✨', '🏰', '💖', '🎀'],
      confetti: ['👑', '💖', '🌸', '✨', '🦄', '🎀', '💜', '⭐', '🌷'],
    },
    texts: {
      familyTitle: 'La Corte del Palacio',
      contributorsStat: 'Hadas madrinas',
      levelsTitle: 'Joyas de la Corona',
      messageTitle: 'Carta de Nuestra Familia',
      supportTitle: 'Mensajes del Palacio',
      emptySupport: '¡Sé el primero en dejar un deseo en el palacio!',
    },
  },
  superheroes: {
    id: 'superheroes',
    name: '🦸 Superhéroes',
    description: 'Rojo, azul y amarillo de cómic. Capas y rayos.',
    swatch: ['#c62828', '#1565c0', '#ffeb3b'],
    colors: colors({
      primary: '#c62828',
      action: '#1565c0',
      actionAlt: '#1e88e5',
      yellow: '#ffeb3b',
      green: '#43a047',
      greenDark: '#2e7d32',
      greenLight: '#81c784',
      purple: '#5e35b1',
      purpleDark: '#4527a0',
      headerBg: '#0d1b3d',
      headerText: '#fff8e1',
      headerSubtitle: '#90caf9',
      bodyFrom: '#e3f2fd',
      bodyMid: '#ffffff',
      bodyTo: '#ffebee',
      progressFrom: '#fffde7',
      progressTo: '#fff176',
      levelsFrom: '#e3f2fd',
      levelsTo: '#bbdefb',
      sectionAccent: '#f44336',
      accent: '#1565c0',
      accentDark: '#0d47a1',
      accentLight: '#90caf9',
      accentBg: '#e3f2fd',
    }),
    emojis: {
      levels: '💥',
      message: '📣',
      messageIcon: '🦸',
      support: '🛡️',
      family: '🦸‍♀️',
      modal: '⚡',
      spark: '💥',
      contributor: '🦸',
      empty: '🏙️',
      hero: ['🦸', '⚡', '💥', '🛡️', '🌟', '🦹', '🚀'],
      confetti: ['⚡', '💥', '🌟', '🦸', '🔵', '🔴', '⭐', '🛡️', '✨'],
    },
    texts: {
      familyTitle: 'La Liga de la Familia',
      contributorsStat: 'Superhéroes',
      levelsTitle: 'Superpoderes',
      messageTitle: 'Mensaje del Cuartel General',
      supportTitle: 'Mensajes de la Liga',
      emptySupport: '¡Sé el primer héroe en dejar un mensaje!',
    },
  },
  deporte: {
    id: 'deporte',
    name: '⚽ Deporte',
    description: 'Verde césped, blanco y naranja. Balones y medallas.',
    swatch: ['#2e7d32', '#fb8c00', '#f1f8e9'],
    colors: colors({
      primary: '#1b5e20',
      action: '#fb8c00',
      actionAlt: '#ffa726',
      yellow: '#ffeb3b',
      green: '#43a047',
      greenDark: '#2e7d32',
      greenLight: '#a5d6a7',
      purple: '#3949ab',
      purpleDark: '#283593',
      headerBg: '#1b5e20',
      headerText: '#f1f8e9',
      headerSubtitle: '#c8e6c9',
      bodyFrom: '#e8f5e9',
      bodyMid: '#ffffff',
      bodyTo: '#f1f8e9',
      progressFrom: '#fffde7',
      progressTo: '#fff59d',
      levelsFrom: '#e8f5e9',
      levelsTo: '#c8e6c9',
      sectionAccent: '#fb8c00',
      accent: '#fb8c00',
      accentDark: '#ef6c00',
      accentLight: '#ffcc80',
      accentBg: '#fff3e0',
    }),
    emojis: {
      levels: '🏆',
      message: '📣',
      messageIcon: '⚽',
      support: '📢',
      family: '🏟️',
      modal: '🏅',
      spark: '🔥',
      contributor: '🏅',
      empty: '🥅',
      hero: ['⚽', '🏆', '🏅', '🔥', '⭐', '🥇', '🎽'],
      confetti: ['⚽', '🏆', '🥇', '🔥', '⭐', '💚', '🧡', '🏅', '🎉'],
    },
    texts: {
      familyTitle: 'El Equipo de Casa',
      contributorsStat: 'Jugadores',
      levelsTitle: 'Fichajes',
      messageTitle: 'Charla del Vestuario',
      supportTitle: 'Ánimos desde la Grada',
      emptySupport: '¡Sé el primero en animar desde la grada!',
    },
  },
  espacio: {
    id: 'espacio',
    name: '🚀 Espacio',
    description: 'Azul noche, morado y plata. Cohetes y planetas.',
    swatch: ['#1a237e', '#7c4dff', '#b3e5fc'],
    colors: colors({
      primary: '#1a237e',
      action: '#7c4dff',
      actionAlt: '#651fff',
      yellow: '#ffd740',
      green: '#00bfa5',
      greenDark: '#00897b',
      greenLight: '#64ffda',
      purple: '#7c4dff',
      purpleDark: '#4527a0',
      headerBg: '#050a1f',
      headerText: '#e8eaf6',
      headerSubtitle: '#9fa8da',
      bodyFrom: '#e8eaf6',
      bodyMid: '#f5f7ff',
      bodyTo: '#d1c4e9',
      progressFrom: '#e3f2fd',
      progressTo: '#b3e5fc',
      levelsFrom: '#ede7f6',
      levelsTo: '#d1c4e9',
      sectionAccent: '#ffab00',
      accent: '#7c4dff',
      accentDark: '#651fff',
      accentLight: '#b388ff',
      accentBg: '#ede7f6',
    }),
    emojis: {
      levels: '🪐',
      message: '📡',
      messageIcon: '🚀',
      support: '🛰️',
      family: '👩‍🚀',
      modal: '🚀',
      spark: '✨',
      contributor: '👨‍🚀',
      empty: '🌌',
      hero: ['🚀', '🪐', '🌟', '🛰️', '🌙', '☄️', '👩‍🚀'],
      confetti: ['🚀', '⭐', '🌟', '🪐', '☄️', '💜', '🔵', '✨', '🌙'],
    },
    texts: {
      familyTitle: 'La Tripulación Espacial',
      contributorsStat: 'Pilotos',
      levelsTitle: 'Etapas del Despegue',
      messageTitle: 'Mensaje desde la Base',
      supportTitle: 'Señales de Apoyo',
      emptySupport: '¡Sé el primero en enviar una señal!',
    },
  },
  dinosaurios: {
    id: 'dinosaurios',
    name: '🦕 Dinosaurios',
    description: 'Verde selva, marrón y naranja. Huellas y volcanes.',
    swatch: ['#33691e', '#8d6e63', '#ff8f00'],
    colors: colors({
      primary: '#33691e',
      action: '#ff8f00',
      actionAlt: '#ffa000',
      yellow: '#ffd54f',
      green: '#689f38',
      greenDark: '#33691e',
      greenLight: '#aed581',
      purple: '#6d4c41',
      purpleDark: '#4e342e',
      headerBg: '#1b3a1a',
      headerText: '#f1f8e9',
      headerSubtitle: '#c5e1a5',
      bodyFrom: '#f1f8e9',
      bodyMid: '#fffde7',
      bodyTo: '#dcedc8',
      progressFrom: '#fff8e1',
      progressTo: '#ffe082',
      levelsFrom: '#f1f8e9',
      levelsTo: '#dcedc8',
      sectionAccent: '#ff8f00',
      accent: '#8d6e63',
      accentDark: '#6d4c41',
      accentLight: '#bcaaa4',
      accentBg: '#efebe9',
    }),
    emojis: {
      levels: '🦖',
      message: '🌋',
      messageIcon: '🦕',
      support: '🦴',
      family: '🥚',
      modal: '🦖',
      spark: '🌿',
      contributor: '🦖',
      empty: '🌴',
      hero: ['🦕', '🦖', '🌋', '🦴', '🌿', '🥚', '🌴'],
      confetti: ['🦕', '🦖', '🌿', '🌋', '🦴', '💚', '🧡', '🌟', '🥚'],
    },
    texts: {
      familyTitle: 'La Manada Jurásica',
      contributorsStat: 'Exploradores',
      levelsTitle: 'Huellas Gigantes',
      messageTitle: 'Mensaje desde la Selva',
      supportTitle: 'Rugidos de Apoyo',
      emptySupport: '¡Sé el primero en dejar tu rugido!',
    },
  },
  mascotas: {
    id: 'mascotas',
    name: '🐾 Mascotas',
    description: 'Menta, crema y marrón. Huellas y corazones.',
    swatch: ['#5d4037', '#26a69a', '#e0f2f1'],
    colors: colors({
      primary: '#5d4037',
      action: '#26a69a',
      actionAlt: '#4db6ac',
      yellow: '#ffe082',
      green: '#66bb6a',
      greenDark: '#2e7d32',
      greenLight: '#a5d6a7',
      purple: '#8d6e63',
      purpleDark: '#5d4037',
      headerBg: '#3e2723',
      headerText: '#efebe9',
      headerSubtitle: '#bcaaa4',
      bodyFrom: '#e0f2f1',
      bodyMid: '#ffffff',
      bodyTo: '#efebe9',
      progressFrom: '#fff8e1',
      progressTo: '#ffe0b2',
      levelsFrom: '#e0f2f1',
      levelsTo: '#b2dfdb',
      sectionAccent: '#ff8a65',
      accent: '#26a69a',
      accentDark: '#00897b',
      accentLight: '#80cbc4',
      accentBg: '#e0f2f1',
    }),
    emojis: {
      levels: '🦴',
      message: '💌',
      messageIcon: '🐶',
      support: '🐾',
      family: '🏡',
      modal: '🐾',
      spark: '💕',
      contributor: '🐾',
      empty: '🐱',
      hero: ['🐶', '🐱', '🐾', '🦴', '💕', '🐰', '🐹'],
      confetti: ['🐾', '💕', '🐶', '🐱', '🦴', '🧡', '💙', '⭐', '✨'],
    },
    texts: {
      familyTitle: 'La Manada de Casa',
      contributorsStat: 'Cuidadores',
      levelsTitle: 'Mimos y Cuidados',
      messageTitle: 'Mensaje de Nuestra Familia',
      supportTitle: 'Cariños de Apoyo',
      emptySupport: '¡Sé el primero en dejar un cariño!',
    },
  },
  musica: {
    id: 'musica',
    name: '🎵 Música',
    description: 'Negro, magenta y amarillo neón. Notas y focos.',
    swatch: ['#212121', '#d500f9', '#ffea00'],
    colors: colors({
      primary: '#6a1b9a',
      action: '#d500f9',
      actionAlt: '#e040fb',
      yellow: '#ffea00',
      green: '#00bfa5',
      greenDark: '#00695c',
      greenLight: '#64ffda',
      purple: '#aa00ff',
      purpleDark: '#6200ea',
      headerBg: '#121212',
      headerText: '#fafafa',
      headerSubtitle: '#ea80fc',
      bodyFrom: '#f3e5f5',
      bodyMid: '#ffffff',
      bodyTo: '#fce4ec',
      progressFrom: '#fffde7',
      progressTo: '#fff59d',
      levelsFrom: '#f3e5f5',
      levelsTo: '#e1bee7',
      sectionAccent: '#ffea00',
      accent: '#d500f9',
      accentDark: '#aa00ff',
      accentLight: '#ea80fc',
      accentBg: '#f3e5f5',
    }),
    emojis: {
      levels: '🎸',
      message: '🎤',
      messageIcon: '🎵',
      support: '🎧',
      family: '🎶',
      modal: '🎵',
      spark: '🎶',
      contributor: '🎸',
      empty: '🎹',
      hero: ['🎵', '🎶', '🎸', '🎤', '🎧', '🌟', '🎹'],
      confetti: ['🎵', '🎶', '🎸', '🎤', '💜', '💛', '⭐', '✨', '🎧'],
    },
    texts: {
      familyTitle: 'La Banda de la Familia',
      contributorsStat: 'Fans',
      levelsTitle: 'Entradas al Concierto',
      messageTitle: 'Mensaje desde el Escenario',
      supportTitle: 'Aplausos',
      emptySupport: '¡Sé el primero en aplaudir!',
    },
  },
  bebe: {
    id: 'bebe',
    name: '👶 Bebé',
    description: 'Pasteles de celeste, rosa y amarillo. Ositos y nubes.',
    swatch: ['#4fc3f7', '#f48fb1', '#fff9c4'],
    colors: colors({
      primary: '#0288d1',
      action: '#f06292',
      actionAlt: '#f48fb1',
      yellow: '#fff59d',
      green: '#81c784',
      greenDark: '#388e3c',
      greenLight: '#c8e6c9',
      purple: '#9575cd',
      purpleDark: '#7e57c2',
      headerBg: '#b3e5fc',
      headerText: '#01579b',
      headerSubtitle: '#0277bd',
      bodyFrom: '#e1f5fe',
      bodyMid: '#ffffff',
      bodyTo: '#fce4ec',
      progressFrom: '#fffde7',
      progressTo: '#fff9c4',
      levelsFrom: '#e1f5fe',
      levelsTo: '#b3e5fc',
      sectionAccent: '#ffb74d',
      accent: '#f06292',
      accentDark: '#ec407a',
      accentLight: '#f8bbd0',
      accentBg: '#fce4ec',
    }),
    emojis: {
      levels: '🧸',
      message: '💌',
      messageIcon: '👶',
      support: '🍼',
      family: '🏠',
      modal: '🧸',
      spark: '☁️',
      contributor: '🍼',
      empty: '🐥',
      hero: ['👶', '🧸', '🍼', '☁️', '⭐', '🐥', '💛'],
      confetti: ['🧸', '🍼', '☁️', '💙', '💗', '💛', '⭐', '✨', '🐥'],
    },
    texts: {
      familyTitle: 'Los Brazos que Acunan',
      contributorsStat: 'Padrinos',
      levelsTitle: 'Primeros Pasos',
      messageTitle: 'Carta para el Peque',
      supportTitle: 'Mensajes con Cariño',
      emptySupport: '¡Sé el primero en dejar un mensaje para el peque!',
    },
  },
  boda: {
    id: 'boda',
    name: '💍 Boda',
    description: 'Blanco, dorado y verde salvia. Anillos y flores.',
    swatch: ['#795548', '#c9a227', '#eef3ea'],
    colors: colors({
      primary: '#795548',
      action: '#c9a227',
      actionAlt: '#e0b93a',
      yellow: '#fff3c4',
      green: '#8fa98a',
      greenDark: '#5c7a5a',
      greenLight: '#c5d6c2',
      purple: '#8e7cc3',
      purpleDark: '#6b5b95',
      headerBg: '#3e3a36',
      headerText: '#faf7f2',
      headerSubtitle: '#d9c9a3',
      bodyFrom: '#faf7f2',
      bodyMid: '#ffffff',
      bodyTo: '#eef3ea',
      progressFrom: '#fff8e1',
      progressTo: '#f3e5ab',
      levelsFrom: '#faf7f2',
      levelsTo: '#efe6d2',
      sectionAccent: '#c9a227',
      accent: '#b0895b',
      accentDark: '#8d6e4b',
      accentLight: '#dcc9a8',
      accentBg: '#f7f1e6',
    }),
    emojis: {
      levels: '🥂',
      message: '💌',
      messageIcon: '💍',
      support: '💐',
      family: '👰',
      modal: '💍',
      spark: '✨',
      contributor: '🕊️',
      empty: '🌿',
      hero: ['💍', '💐', '🥂', '✨', '🕊️', '🌿', '💛'],
      confetti: ['💍', '🥂', '🌸', '✨', '🕊️', '💛', '🤍', '💚', '🌿'],
    },
    texts: {
      familyTitle: 'Los Invitados de Honor',
      contributorsStat: 'Invitados',
      levelsTitle: 'Regalos de Boda',
      messageTitle: 'Mensaje de los Novios',
      supportTitle: 'Buenos Deseos',
      emptySupport: '¡Sé el primero en dejar un buen deseo!',
    },
  },
  verano: {
    id: 'verano',
    name: '🏖️ Verano',
    description: 'Azul cielo, amarillo sol y coral. Olas y helados.',
    swatch: ['#039be5', '#ffca28', '#ff7043'],
    colors: colors({
      primary: '#0277bd',
      action: '#ff7043',
      actionAlt: '#ff8a65',
      yellow: '#ffca28',
      green: '#26a69a',
      greenDark: '#00796b',
      greenLight: '#80cbc4',
      purple: '#5c6bc0',
      purpleDark: '#3949ab',
      headerBg: '#0277bd',
      headerText: '#e1f5fe',
      headerSubtitle: '#b3e5fc',
      bodyFrom: '#e1f5fe',
      bodyMid: '#fffde7',
      bodyTo: '#fff3e0',
      progressFrom: '#fff8e1',
      progressTo: '#ffe082',
      levelsFrom: '#e0f7fa',
      levelsTo: '#b2ebf2',
      sectionAccent: '#ffca28',
      accent: '#ff7043',
      accentDark: '#e64a19',
      accentLight: '#ffab91',
      accentBg: '#fbe9e7',
    }),
    emojis: {
      levels: '🍦',
      message: '🐚',
      messageIcon: '🏖️',
      support: '🌊',
      family: '⛱️',
      modal: '☀️',
      spark: '☀️',
      contributor: '🌴',
      empty: '🏝️',
      hero: ['☀️', '🌊', '🏖️', '🍦', '🐚', '🌴', '⛱️'],
      confetti: ['☀️', '🌊', '🍦', '🐚', '💛', '💙', '🧡', '⭐', '🌴'],
    },
    texts: {
      familyTitle: 'La Pandilla de la Playa',
      contributorsStat: 'Veraneantes',
      levelsTitle: 'Olas de Ayuda',
      messageTitle: 'Postal de Nuestra Familia',
      supportTitle: 'Mensajes en la Arena',
      emptySupport: '¡Sé el primero en escribir en la arena!',
    },
  },
  halloween: {
    id: 'halloween',
    name: '🎃 Halloween',
    description: 'Naranja, negro y morado. Calabazas y fantasmas.',
    swatch: ['#ef6c00', '#212121', '#6a1b9a'],
    colors: colors({
      primary: '#ef6c00',
      action: '#ef6c00',
      actionAlt: '#ff9800',
      yellow: '#ffca28',
      green: '#7cb342',
      greenDark: '#558b2f',
      greenLight: '#aed581',
      purple: '#6a1b9a',
      purpleDark: '#4a148c',
      headerBg: '#1a1a1a',
      headerText: '#ffe0b2',
      headerSubtitle: '#ce93d8',
      bodyFrom: '#ede7f6',
      bodyMid: '#fff3e0',
      bodyTo: '#e1bee7',
      progressFrom: '#fff3e0',
      progressTo: '#ffcc80',
      levelsFrom: '#f3e5f5',
      levelsTo: '#e1bee7',
      sectionAccent: '#ff9800',
      accent: '#8e24aa',
      accentDark: '#6a1b9a',
      accentLight: '#ce93d8',
      accentBg: '#f3e5f5',
    }),
    emojis: {
      levels: '🎃',
      message: '📜',
      messageIcon: '👻',
      support: '🕸️',
      family: '🏚️',
      modal: '🎃',
      spark: '🦇',
      contributor: '👻',
      empty: '🕯️',
      hero: ['🎃', '👻', '🦇', '🕸️', '🍬', '🌙', '🕯️'],
      confetti: ['🎃', '👻', '🦇', '🍬', '🧡', '💜', '⭐', '🕸️', '✨'],
    },
    texts: {
      familyTitle: 'La Casa Encantada',
      contributorsStat: 'Fantasmas',
      levelsTitle: 'Truco o Trato',
      messageTitle: 'Mensaje desde la Cripta',
      supportTitle: 'Susurros de Apoyo',
      emptySupport: '¡Sé el primero en dejar un susurro!',
    },
  },
};

export function isThemeId(value: unknown): value is ThemeId {
  return (
    typeof value === 'string' &&
    (THEME_IDS as readonly string[]).includes(value)
  );
}

/** Tema por id; cualquier valor desconocido devuelve el tema por defecto. */
export function getTheme(id: string | null | undefined): Theme {
  return isThemeId(id) ? THEMES[id] : THEMES[DEFAULT_THEME_ID];
}

/** CSS con un bloque `html[data-theme="id"]` por tema que sobrescribe los tokens. */
export function themeCss(): string {
  return THEME_IDS.map((id) => {
    const decl = Object.entries(THEMES[id].colors)
      .map(([k, v]) => `${k}:${v}`)
      .join(';');
    return `html[data-theme="${id}"]{${decl}}`;
  }).join('\n');
}
